version: "3"
services:
  edraak-judge-api:
    build:
      context: ${DEVSTACK_WORKSPACE}/edraak-judge/.
      dockerfile: ${DEVSTACK_WORKSPACE}/edraak-judge/Dockerfile
    ports:
      - "5000:80"
    env_file:
      - ${DEVSTACK_WORKSPACE}/edraak-judge/.env
    container_name: edraak.devstack.judge
    depends_on:
      - edraak-judge-redis
    volumes:
      - ${DEVSTACK_WORKSPACE}/edraak-judge:/app

  edraak-judge-worker:
    build:
      context: ${DEVSTACK_WORKSPACE}/edraak-judge/.
      dockerfile: ${DEVSTACK_WORKSPACE}/edraak-judge/Dockerfile
    env_file:
      - ${DEVSTACK_WORKSPACE}/edraak-judge/.env
    command: rq worker --url redis://edraak-judge-redis:6379/0
    depends_on:
      - edraak-judge-redis
    volumes:
      - ${DEVSTACK_WORKSPACE}/edraak-judge:/app

  edraak-judge-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"

  edraak_programs:
    depends_on:
      - mysql
      - mongo
      - memcached
      - edraak-judge-api

  edraak_dev_router:
    depends_on:
      - lms
      - studio
      - edraak_marketing
      - edraak_programs
      - edraak-judge-api
    networks:
      default:
        aliases:
          - www.edraak.dev
          - courses.edraak.dev
          - programs.edraak.dev
          - edraak.dev
          - judge.edraak.dev
